# Use an official Node.js runtime as the base image
FROM node:20

# Install pnpm globally
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml ./

# Install app dependencies using pnpm
RUN pnpm install

# Copy the rest of the app source code to the working directory
COPY . .

# Expose a port for the app to listen on
EXPOSE 3000:3000

# Define the command to run the app
CMD [ "pnpm", "dev" ]
