export const interests: string[] = [
  'Advertising',
  'Agriculture',
  'Architecture',
  'Aviation',
  'Banking',
  'Investment banking',
  'Online banking',
  'Retail banking',
  'Business',
  'Construction',
  'Design',
  'Fashion design',
  'Graphic design',
  'Interior design',
  'Economics',
  'Engineering',
  'Entrepreneurship',
  'Health care',
  'Higher education',
  'Management',
  'Marketing',
  'Nursing',
  'Online',
  'Digital marketing',
  'Display advertising',
  'Email marketing',
  'Online advertising',
  'Search engine optimization',
  'Social media',
  'Social media marketing',
  'Web design',
  'Web development',
  'Web hosting',
  'Personal finance',
  'Creditcards',
  'Insurance',
  'Investment',
  'Mortgage loans',
  'Real estate',
  'Retail',
  'Sales',
  'Science',
  'Small business',
  'Games',
  'Action games',
  'Board games',
  'Browser games',
  'Card games',
  'Casino games',
  'First - person shooter games',
  'Gambling',
  'Massively multiplayer online games',
  'Massively multiplayer online role - playing games',
  'Online games',
  'Online poker',
  'Puzzle video games',
  'Racing games',
  'Role - playing games',
  'Shooter games',
  'Simulation games',
  'Sports games',
  'Strategy games',
  'Video games',
  'Word games',
  'Live events',
  'Ballet',
  'Bars',
  'Concerts',
  'Dancehalls',
  'Music festivals',
  'Nightclubs',
  'Parties',
  'Plays',
  'Theatre',
  'Movies',
  'Action movies',
  'Animated movies',
  'Anime movies',
  'Bollywood movies',
  'Comedy movies',
  'Documentary movies',
  'Drama movies',
  'Fantasy movies',
  'Horror movies',
  'Musical theatre',
  'Science fiction movies',
  'Thriller movies',
  'Music',
  'Blues music',
  'Classical music',
  'Country music',
  'Dance music',
  'Electronic music',
  'Gospel music',
  'Heavy metal music',
  'Hip hop music',
  'Jazz music',
  'Music videos',
  'Pop music',
  'Rhythm and blues music',
  'Rock music',
  'Soul music',
  'Reading',
  'Books',
  'Comics',
  'E - books',
  'Fiction books',
  'Literature',
  'Magazines',
  'Manga',
  'Mystery fiction',
  'Newspapers',
  'Non - fiction books',
  'Romance novels',
  'TV',
  'TV comedies',
  'TV game shows',
  'TV reality shows',
  'TV talkshows',
  'Dating',
  'Family',
  'Fatherhood',
  'Friendship',
  'Marriage',
  'Motherhood',
  'Parenting',
  'Weddings',
  'Bodybuilding',
  'Meditation',
  'Physical exercise',
  'Physical fitness',
  'Running',
  'Weight training',
  'Yoga',
  'Alcoholic beverages',
  'Beer',
  'Distilled beverage',
  'Wine',
  'Beverages',
  'Coffee',
  'Energy drinks',
  'Juice',
  'Soft drinks',
  'Tea',
  'Cooking',
  'Baking',
  'Recipes',
  'Cuisine',
  'Chinese cuisine',
  'French cuisine',
  'German cuisine',
  'Greek cuisine',
  'Indian cuisine',
  'Italian cuisine',
  'Japanese cuisine',
  'Korean cuisine',
  'Latin American cuisine',
  'Mexican cuisine',
  'Middle Eastern cuisine',
  'Spanish cuisine',
  'Thai cuisine',
  'Vietnamese cuisine',
  'Food',
  'Barbecue',
  'Chocolate',
  'Desserts',
  'Fast food',
  'Organic food',
  'Pizza',
  'Seafood',
  'Veganism',
  'Vegetarianism',
  'Restaurants',
  'Coffeehouses',
  'Diners',
  'Fast casual restaurants',
  'Fast food restaurants',
  'Arts and music',
  'Acting',
  'Crafts',
  'Dance',
  'Drawing',
  'Drums',
  'Fine art',
  'Guitar',
  'Painting',
  'Performing arts',
  'Photography',
  'Sculpture',
  'Singing',
  'Writing',
  'Current events',
  'Home and garden',
  'Do it yourself(DIY)',
  'Furniture',
  'Gardening',
  'Home Appliances',
  'Home improvement',
  'Pets',
  'Birds',
  'Cats',
  'Dogs',
  'Fish',
  'Horses',
  'Pet food',
  'Rabbits',
  'Reptiles',
  'Politics and social issues',
  'Charity and causes',
  'Community issues',
  'Environmentalism',
  'Law',
  'Military',
  'Politics',
  'Religion',
  'Sustainability',
  'Veterans',
  'Volunteering',
  'Travel',
  'Adventure travel',
  'Air travel',
  'Beaches',
  'Car rentals',
  'Cruises',
  'Ecotourism',
  'Hotels',
  'Lakes',
  'Mountains',
  'Nature',
  'Theme parks',
  'Tourism',
  'Vacations',
  'Vehicles',
  'Automobiles',
  'Boats',
  'Electric vehicle',
  'Hybrids',
  'Minivans',
  'Motorcycles',
  'RVs',
  'SUVs',
  'Scooters',
  'Trucks',
  'Beauty',
  'Beauty salons',
  'Cosmetics',
  'Fragrances',
  'Hair products',
  'Spas',
  'Tattoos',
  'Clothing',
  'Children’s clothing',
  'Men’s clothing',
  'Shoes',
  'Women’s clothing',
  'Fashion accessories',
  'Dresses',
  'Handbags',
  'Jewelry',
  'Sunglasses',
  'Shopping',
  'Boutiques',
  'Coupons',
  'Discount stores',
  'Luxury goods',
  'Online shopping',
  'Shopping malls',
  'Toys',
  'Outdoor recreation',
  'Boating',
  'Camping',
  'Fishing',
  'Horseback riding',
  'Hunting',
  'Mountain biking',
  'Surfing',
  'Sports',
  'American football',
  'Association football(Soccer)',
  'Auto racing',
  'Baseball',
  'Basketball',
  'College football',
  'Golf',
  'Marathons',
  'Skiing',
  'Snowboarding',
  'Swimming',
  'Tennis',
  'Thriathlons',
  'Volleyball',
  'Computers',
  'Computer memory',
  'Computer monitors',
  'Computer processors',
  'Computer servers',
  'Desktop computers',
  'Free software',
  'Hard drives',
  'Network storage',
  'Software',
  'Tablet computers',
  'Consumer electronics',
  'Audio equipment',
  'Camcorders',
  'Cameras',
  'E - book readers',
  'GPS devices',
  'Game consoles',
  'Mobile phones',
  'Portable media players',
  'Projectors',
  'Smartphones',
  'Televisions',
];
